apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-two-deployment
spec:
  selector:
    matchLabels:
      app: nginx-two
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx-two
    spec:
      containers:
      - name: nginx-two
        image: docker.io/bitnami/cassandra:4.0
        ports:
        - containerPort: 80
          name: nginx-pod-port

